import csv

with open("data/data.csv", "w", newline="",encoding="utf-8") as f:
    writer = csv.DictWriter(f, fieldnames=["congviec", "key"])
    writer.writeheader()
    writer.writerow({"congviec": "Front End ", "key": "Khoa học máy tính/Công nghệ thông tin/Hệ thống thông tin/Công nghệ phần mềm, Khoa học máy tính/Công nghệ thông tin/Công nghệ phần mềm// Front End, Front End, Front End ,FrontEnd, FrontEnd, FrontEnd//HTML, CSS, JS, JavaScrip, jQuery, Bootstrap, HTML, CSS, JS, JavaScrip, jQuery, Bootstrap, AngularJS, ReactJS, VueJs, NodeJS, Photoshop, UI/UX, API,REST, JSON, UNIT TEST, XSS, CSRF, ES6, typescript/3 năm/Chứng chỉ B1/Khả năng đọc hiểu tài liệu tiếng Anh tốt/Quận 7,TPHCM/10 triệu"})
    writer.writerow({"congviec": "Front End SENIOR", "key": "Khoa học máy tính/Công nghệ thông tin/Hệ thống thông tin/Công nghệ phần mềm, Khoa học máy tính/Công nghệ thông tin/Công nghệ phần mềm// docker, kubernet, cdn, docker, kubernet, cdn,//Front End, Front End, Front End ,FrontEnd, FrontEnd, FrontEnd// HTML, CSS, JS, JavaScrip, jQuery, Bootstrap,HTML, CSS, JS, JavaScrip, jQuery, Bootstrap,	 AngularJS, ReactJS, VueJs, NodeJS, Photoshop, UI/UX, API,REST, JSON, UNIT TEST, XSS, CSRF, ES6, typescript/3 năm/Khả năng giao tiếp tốt /Tân Bình,TPHCM/ 6 triệu"})
    writer.writerow({"congviec": "BackEnd .NET", "key": "Khoa học máy tính/Công nghệ thông tin/Hệ thống thông tin/Hệ thống thông tin/Công nghệ phần mềm,Hệ thống thông tin//BackEnd , BackEnd, BackEnd,Back End , Back End, Back End //.NET, .NET, .NET,// C#, ASP.NET, MVC, MongoDB, CouchBase, Redis, RabbitMQ, SQL Server, MySQL, PostgreSQL, OOP, Design Pattern, SOLID, SOA/Micro Service/1 năm /Khả năng giao tiếp bằng tiếng Nhật tốt/Gò Vấp, TPHCM/10 triệu"})
    writer.writerow({"congviec": "BackEnd","key": "Khoa học máy tính/Công nghệ thông tin/Hệ thống thông tin/Hệ thống thông tin/Công nghệ phần mềm,Hệ thống thông tin//BackEnd , BackEnd, BackEnd,Back End , Back End, Back End //Javascript, Typescript, Express, Socket, NestJS, jQuery, VueJS, ReactJS ,JavaScriptNode JS, React JS,MongoDB, MySQL, Serverless, Lambda, FFmpeg, NOSQL, SOAP, RESTfull, JSON, Oracle SQL, PL/SQL, PHP, Java, J2EELaravel, AJAX,MVCYii2, Codeigniter, Cake, WordPress/Không có kinh nghiệm/Chứng chỉ B1/Bình Thạnh,TPHCM/Quận 12, TPHCM/8 triệu"})
    writer.writerow({"congviec": "Lập Trình viên","key": "Khoa học máy tính/Công nghệ thông tin/Hệ thống thông tin/Công nghệ phần mềm,DEV, Java, C#,  PHP, Angular, OOP, C++, Python, PHP, DEV, Java, C#,  PHP, Angular, OOP, C++, Python, PHP, DEV, Java, C#,  PHP, Angular, OOP, C++, Python, PHP, Khoa học máy tính/Công nghệ thông tin/Hệ thống thông tin/Công nghệ phần mềm, Khoa học máy tính/Công nghệ thông tin/Hệ thống thông tin/Công nghệ phần mềm , Spring, Microservices, Rest API, .Net Core, Php Laravel, Angular, ReactJS, Hibernate, Mysql, Oracle, Sql server NoSQL, SOAP/OAP/Restful, JSON, XML, OOP, Design pattern, Git, Jira, TFS,Oralce, MySQL, SQL Server, MVC, Struts, Socket.io, VueJS, Movable Type, Design pattern, Flask,NuxtJS, Buefy /Không có kinh nghiệm/Chứng chỉ B1/ Quận 3,TPHCM/7 triệu"})
    writer.writerow({"congviec": "Quản Trị Cơ Sở Dữ Liệu","key": "Khoa học máy tính/Công nghệ thông tin/Hệ thống thông tin/Công nghệ phần mềm,Hệ thống thông tin Oracle Database, SQL Server,Oracle Database, SQL Server,Oracle Database, SQL Server, MySQL, DB2, RAC, Tuning, T-SQL, PL/SQL, CSDL SQL, Oracle, MySQL, PostGres, MongoDB, PowerBI, Qlik, Tableau, CentOS, Ubuntu, Windows, Linux, Unix,  OCA, OCP, OCM, MCTS, MCITP, MCM... OCA, OCP, OCM, MCTS, MCITP, MCM.../Không có kinh nghiệm/Chứng chỉ B1/Gò Vấp, TPHCM/10 triệu"})
    writer.writerow({"congviec": "Tester (QA)","key": "Khoa học máy tính/Công nghệ thông tin/Hệ thống thông tin/Công nghệ phần mềm,test case, checklist, run testcase, viết bug, report bug, Automation testing, test case, checklist, run testcase, viết bug, report bug, Automation testing,// Test specs, System Test Cases, communicate, teamwork, QA/QC, ux/ui, QA/QC, ux/ui, Jira, confluent, figma/ 1 năm/Chứng chỉ B1/Gò Vấp, TPHCM/10 triệu"})
    writer.writerow({"congviec": "Thiết kế web","key": "Khoa học máy tính/Công nghệ thông tin/Hệ thống thông tin/Công nghệ phần mềm,Công nghệ phần mềm,website, design, Photoshop, AI, InDesign,Ps, website, design, Photoshop, AI, InDesign,Ps, thiết kế, thẩm mỹ tốt, sáng tạo, Xd, Responsive, Figma, Ux/ui, HTML/CSS/Javascript, Boostrap, Layout, Illustrator, Sketch, CMS WordPress (WooCommerce), eCommerce Platform, templates/Không yêu cầu kinh nghiệm/Chứng chỉ B1/Gò Vấp, TPHCM/10 triệu"})







